services:
  backend:
    container_name: ccc-be
    image: bibi1211/ccc-be:v1.0
    environment:
      APP_ENV: local
      HOST: 0.0.0.0
      PORT: 8000
      CORS_ORIGINS:
      X-API-KEY: 123456
      DATABASE_URL: postgresql+psycopg://admin:b@postgres-container:5432/ccc
      POSTGRES_HOST: postgres-container
      POSTGRES_PORT: 5432
      POSTGRES_DB: ccc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: b
    ports:
      - "8000:8000"
    networks:
      #- env_postgres_shared
      - postgres_shared-network
    restart: unless-stopped

networks:
  #nv_postgres_shared:
  postgres_shared-network:
    external: true
